# Generated by Django 5.0.1 on 2024-02-23 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0010_alter_inboxmessage_content_id"),
        ("likes", "0004_alter_like_content_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="author",
        ),
        migrations.AddField(
            model_name="like",
            name="receive_author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_like",
                to="identity.author",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="like",
            name="send_author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_like",
                to="identity.author",
            ),
            preserve_default=False,
        ),
    ]
