# Generated by Django 5.0.1 on 2024-02-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0006_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='content_id',
            field=models.CharField(max_length=255),
        ),
    ]
