# Generated by Django 5.0.1 on 2024-02-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_remove_author_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='url',
            new_name='profile_url',
        ),
    ]
