# Generated by Django 5.0.1 on 2024-02-22 18:53

import deadlybird.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_author_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default=deadlybird.util.generate_next_id, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inboxmessage',
            name='id',
            field=models.CharField(default=deadlybird.util.generate_next_id, max_length=10, primary_key=True, serialize=False),
        ),
    ]
