# Generated by Django 5.0.1 on 2024-02-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_author_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxmessage',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('follow', 'Follow'), ('Like', 'Like'), ('comment', 'Comment')], max_length=50),
        ),
    ]
