# Generated by Django 5.0.1 on 2024-03-19 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_alter_inboxmessage_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_github_check',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
