# Generated by Django 5.0.1 on 2024-03-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_author_last_github_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_github_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
