# Generated by Django 5.0.1 on 2024-04-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0016_author_last_github_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
