# Generated by Django 5.0.1 on 2024-04-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0017_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
