# Generated by Django 5.0.1 on 2024-04-09 07:45

import deadlybird.util
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_alter_author_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedAuthor',
            fields=[
                ('id', models.CharField(default=deadlybird.util.generate_next_id, max_length=255, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_origin_author', to='identity.author')),
                ('blocked_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_author', to='identity.author')),
            ],
            options={
                'unique_together': {('author', 'blocked_author')},
            },
        ),
    ]
