# Generated by Django 5.0.1 on 2024-04-07 17:31

import deadlybird.util
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0016_author_last_github_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.author')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(default=deadlybird.util.generate_next_id, max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=7)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.author')),
            ],
        ),
    ]
