# Generated by Django 5.0.1 on 2024-04-10 19:27

import deadlybird.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.CharField(default=deadlybird.util.generate_next_id, max_length=255, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain'), ('application/base64', 'Application Base64'), ('image/png;base64', 'Png Base64'), ('image/jpeg;base64', 'Jpeg Base64')], max_length=30)),
                ('content', models.TextField()),
            ],
        ),
    ]
