# Generated by Django 5.0.1 on 2024-02-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.URLField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
