# Generated by Django 5.0.1 on 2024-02-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_alter_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
