# Generated by Django 5.0.1 on 2024-02-23 23:24

import deadlybird.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_node_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.CharField(default=deadlybird.util.generate_next_id, max_length=255, primary_key=True, serialize=False),
        ),
    ]
