# Generated by Django 5.0.1 on 2024-02-25 19:33

import nodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_alter_node_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='password',
            new_name='outgoing_password',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='username',
            new_name='outgoing_username',
        ),
        migrations.AddField(
            model_name='node',
            name='incoming_password',
            field=models.CharField(default=nodes.models.generate_random_credential, max_length=255),
        ),
        migrations.AddField(
            model_name='node',
            name='incoming_username',
            field=models.CharField(default=nodes.models.generate_random_credential, max_length=255),
        ),
    ]
