# Generated by Django 5.0.1 on 2024-02-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_rename_password_node_outgoing_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='incoming_password',
        ),
        migrations.RemoveField(
            model_name='node',
            name='incoming_username',
        ),
    ]
