# Generated by Django 5.0.1 on 2024-02-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.IntegerField(choices=[(0, 'text/markdown'), (1, 'text/plain'), (2, 'application/base64'), (3, 'image/png;base64'), (4, 'image/jpeg;base64')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.IntegerField(choices=[(0, 'text/markdown'), (1, 'text/plain'), (2, 'application/base64'), (3, 'image/png;base64'), (4, 'image/jpeg;base64')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'PUBLIC'), (1, 'FRIENDS'), (2, 'UNLISTED')]),
        ),
    ]
