# Generated by Django 5.0.1 on 2024-02-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_content_type_alter_post_content_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategoryMeta',
        ),
    ]
