# Generated by Django 5.0.1 on 2024-03-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_alter_inboxmessage_content_type'),
        ('posts', '0008_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='origin_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_author', to='identity.author'),
        ),
        migrations.AddField(
            model_name='post',
            name='origin_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain')], max_length=30),
        ),
    ]
