# Generated by Django 5.0.1 on 2024-03-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_origin_author_post_origin_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
