# Generated by Django 5.0.1 on 2024-04-08 20:45

import deadlybird.util
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_alter_author_profile_picture'),
        ('posts', '0010_alter_post_origin_alter_post_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='origin_author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='origin_post',
        ),
        migrations.CreateModel(
            name='FollowingFeedPost',
            fields=[
                ('id', models.CharField(default=deadlybird.util.generate_next_id, max_length=255, primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_follower', to='identity.author')),
                ('from_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_from_author', to='identity.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
