# Generated by Django 5.0.1 on 2024-04-09 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_alter_author_profile_picture'),
        ('posts', '0011_remove_post_origin_author_remove_post_origin_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='origin_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_origin_author', to='identity.author'),
        ),
    ]
